
all: array.exe linked_list.exe dyn_array.exe

array.exe: array.cpp
	g++ -Wall array.cpp -o array.exe

linked_list.exe: linked_list.cpp
	g++ -Wall linked_list.cpp -o linked_list.exe

dyn_array.exe: dyn_array.cpp
	g++ -Wall dyn_array.cpp -o dyn_array.exe

clean:
	rm *.exe